version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "tuesday"
          time: "09:00"
          timezone: "UTC"
      open-pull-requests-limit: 5
      labels:
          - "dependencies"
          - "automated"
      groups:
          react-ecosystem:
              patterns:
                  - "react*"
                  - "@types/react*"
          radix-ui:
              patterns:
                  - "@radix-ui/*"
          build-tools:
              patterns:
                  - "next*"
                  - "tailwind*"
                  - "@tailwindcss/*"
          dev-tooling:
              patterns:
                  - "@biomejs/*"
                  - "prettier*"
                  - "typescript"
                  - "@types/*"
      allow:
          - dependency-type: "direct"
            update-type: "version-update:semver-patch"
          - dependency-type: "direct"
            update-type: "version-update:semver-minor"
        # Ignore major version updates for critical packages (manual review needed)
      ignore:
          - dependency-name: "react"
            update-types: ["version-update:semver-major"]
          - dependency-name: "react-dom"
            update-types: ["version-update:semver-major"]
          - dependency-name: "next"
            update-types: ["version-update:semver-major"]
        # Custom commit message
      commit-message:
          prefix: "deps"
          prefix-development: "deps-dev"
          include: "scope"
      rebase-strategy: "auto"
        # Only check for security updates on weekends for non-critical deps
      target-branch: "main"

    # GitHub Actions - less frequent, security-focused
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "monthly"
          day: "monday"
          time: "10:00"
          timezone: "UTC"
      open-pull-requests-limit: 3
      labels:
          - "dependencies"
          - "github-actions"
          - "automated"
      commit-message:
          prefix: "ci"
      rebase-strategy: "auto"
        # Group all action updates together
      groups:
          github-actions:
              patterns:
                  - "*"

    # Security-only updates (runs daily for critical security patches)
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "06:00"
          timezone: "UTC"
      open-pull-requests-limit: 2
      labels:
          - "security"
          - "critical"
          - "automated"
        # Only security updates
      allow:
          - dependency-type: "direct"
            update-type: "security-update"
          - dependency-type: "indirect"
            update-type: "security-update"
      commit-message:
          prefix: "security"
      rebase-strategy: "auto"