version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/" # Location of package.json
      schedule:
          interval: "weekly"
          day: "monday"
      groups:
          react-framework:
              patterns:
                  - "next"
                  - "react"
                  - "react-dom"
                  - "@types/react"
                  - "@types/react-dom"
          radix-ui:
              patterns:
                  - "@radix-ui/*"
          tailwindcss:
              patterns:
                  - "tailwindcss"
                  - "tailwindcss-animate"
                  - "tailwind-merge"
                  - "@tailwindcss/postcss"
                  - "postcss"
                  - "prettier-plugin-tailwindcss"
          prettier:
              patterns:
                  - "prettier"
                  - "prettier-plugin-*"
          biome:
              patterns:
                  - "@biomejs/biome"
          typescript-types:
              patterns:
                  - "@types/*"